CREATE TABLE IF NOT EXISTS `city` (
  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `name` TEXT NOT NULL UNIQUE,
  `short` TEXT NOT NULL UNIQUE
);
INSERT INTO `city` VALUES (null, 'Kraków', 'krk');
INSERT INTO `city` VALUES (null, 'Miszkolc', 'misz');
